package main

import (
	"fmt"
	"mapreduce"
	"os"
	"strconv"
	"strings"
	"unicode"
)

//
// The map function is called once for each file of input. The first
// argument is the name of the input file, and the second is the
// file's complete contents. You should ignore the input file name,
// and look only at the contents argument. The return value is a slice
// of key/value pairs.
//
func mapF(filename string, contents string) []mapreduce.KeyValue {
	// Your code here (Part II).
	wordCnt := make(map[string]int)
	splicFunc := func(c rune) bool {
		return !unicode.IsLetter(c)
	}
	words := strings.FieldsFunc(contents, splicFunc)
	for _, word := range words {
		wordCnt[word]++
	}
	keyValuePairs := make([]mapreduce.KeyValue, len(wordCnt))
	for word, cnt := range wordCnt {
		keyValuePairs = append(keyValuePairs, mapreduce.KeyValue{Key:word, Value:strconv.Itoa(cnt)})
	}
	return keyValuePairs
}

//
// The reduce function is called once for each key generated by the
// map tasks, with a list of all the values created for that key by
// any map task.
//
func reduceF(key string, values []string) string {
	// Your code here (Part II).

	totalCnt := int64(0)
	for _, x := range values {
		//Notice. If the appearance count of key is empty string, function ParseInt may throw error
		if x == "" {
			continue
		}
		if cnt, err := strconv.ParseInt(x, 10, 64); err == nil {
			totalCnt += cnt
		} else {
			panic(err)
		}
	}
	return strconv.Itoa(int(totalCnt))
}

// Can be run in 3 ways:
// 1) Sequential (e.g., go run wc.go master sequential x1.txt .. xN.txt)
// 2) Master (e.g., go run wc.go master localhost:7777 x1.txt .. xN.txt)
// 3) Worker (e.g., go run wc.go worker localhost:7777 localhost:7778 &)
func main() {
	if len(os.Args) < 4 {
		fmt.Printf("%s: see usage comments in file\n", os.Args[0])
	} else if os.Args[1] == "master" {
		var mr *mapreduce.Master
		if os.Args[2] == "sequential" {
			mr = mapreduce.Sequential("wcseq", os.Args[3:], 3, mapF, reduceF)
		} else {
			mr = mapreduce.Distributed("wcseq", os.Args[3:], 3, os.Args[2])
		}
		mr.Wait()
	} else {
		mapreduce.RunWorker(os.Args[2], os.Args[3], mapF, reduceF, 100, nil)
	}
}
